# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b048ad3e279aace1334bfa19ecdd2650774163cb001d22982a4efe4c30513fbd3daced7ec65d119583e92ea4b80cce33dac47dde7a958a5070932d5b3eb2a5cd

test:
  secret_key_base: cb17d5d5607dcdc46bda6996bb1481469d2d784ee5bccf2ddf0c0d726c884d8901a5df7e988ffea74637868306a982d08da2327ba7d5f12acf3e933df5ef1fa0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
